/**
 * NaN — diccionario central de UI (EN origen + ES).
 * Convención del proyecto: todo string de UI vive aquí (CLAUDE.md).
 * Voz: docs/brand/nan-voz.md §9. Sin em dashes. snake_case solo en identificadores técnicos.
 *
 * Uso en un componente/página:
 *   import { getLang, useT } from '../i18n/ui';
 *   const lang = getLang(Astro.url);
 *   const tt = useT(lang);
 */

const ui = {
  en: {
    meta: {
      title: 'NaN — Build without limits',
      description:
        'A community of builders sharing GPUs to run open models at a flat rate. OpenAI-compatible API, zero logs, spots limited by compute.',
      siteName: 'NaN',
      ogLocale: 'en_US',
    },
    // strings que solo ve la tecnología asistiva. {x} = hueco a sustituir.
    a11y: {
      skip: 'Skip to content',
      brandHome: 'NaN, home',
      menuOpen: 'Open menu',
      menuClose: 'Close menu',
      navPrimary: 'Primary',
      navLegal: 'Legal',
      navDocs: 'Docs sections',
      language: 'Language',
      email: 'Email',
      region: 'Region',
      close: 'Close',
      cookies: 'Cookie notice',
      projectDetail: 'Project detail',
      openProject: 'Open {name}',
      projectsRail: 'Community projects, horizontal carousel',
      membersOnly: '{title}, members only',
      gpuDither: 'NVIDIA RTX 5090, dithered illustration',
    },
    nav: {
      models: 'Models',
      community: 'Community',
      events: 'Events',
      projects: 'Projects',
      docs: 'Docs',
      login: 'Login',
    },
    hero: {
      line1: 'Build without',
      line2: 'limits.',
      sub: "Don't run out of tokens. Ever.",
      body:
        'NaN is the community of builders sharing GPUs to run AI open models. Build whatever you need, with no token cap. You can just do things.',
      spots: 'Limited spots',
      waitline: 'Join the waitlist to unlock your subscription. Just leave your email.',
      emailPlaceholder: 'you@email.dev',
      regionLabel: 'Select your Region',
      submit: 'Join waitlist',
      // estados del envío (los lee waitlist.ts desde data-* del <form>)
      sending: 'Sending…',
      okRegistered: "You're on the waitlist.",
      okPosition: 'position',
      okText: "We'll approve your spot in the next few days. Keep an eye on your inbox ^__^",
      errEmail: 'That email does not look valid.',
      errRegion: 'Pick a region.',
      errNetwork: 'The network failed, not you. Try again.',
      errGeneric: 'Something broke on our side. Try again in a bit.',
    },
    why: {
      label: 'what is nan',
      title1: 'What is NaN.',
      title2: 'The Builders Community',
      lead: 'Builders sharing dedicated GPUs to run open models and burn tokens without limits.',
      p: [
        'Closed-model APIs are convenient but expensive and limited. Open models are free but running them seriously requires hardware almost no one has at home.',
        'NaN solves this by sharing powerful GPUs among builders who actually use them, splitting the real cost of infrastructure.',
        'A closed community by design, limited to the real capacity of shared GPUs. When it fills up, we open a waitlist.',
        'The community lives on Discord. The website only manages access. Every member pays to be here. Only those who truly want to build make it in.',
      ],
    },
    built: {
      label: 'built with nan',
      title1: "We don't burn tokens.",
      title2: 'We build.',
      sub: 'Real projects built by NaN members using the shared inference cluster. This is what happens when builders get serious hardware.',
      railLabel: 'community projects',
      seeAll: 'See all projects',
      addYours: 'Add yours',
    },
    models: {
      label: 'the cluster',
      titleSuffix: 'models.',
      titleLine2: 'One API.',
      sub: 'The full open-model inference stack, voted by the community every quarter. Data stays in the EU, with nothing logged.',
      unmetered: 'unmetered',
      cta: 'Join the waitlist',
    },
    privacy: {
      label: 'privacy',
      title1: 'Pure inference.',
      title2: 'Zero logs.',
      intro:
        "NaN is inference infrastructure. There's no logging of prompts, model responses, nothing. Everything lives in your local session, on whatever client, agent or custom app you use.",
      guarantees: [
        'Zero logs. No prompt or response logging.',
        'Everything lives in your local client or agent session.',
        'Processing in the European Union.',
        "Your code doesn't train any models.",
        'Server metrics only, for cluster maintenance (tokens/s, RPM).',
      ],
      termNote: '# 0 bytes. 0 rows. nothing stored, by design.',
      termFoot: 'leaving the server: tokens/s · RPM · cluster metrics',
    },
    pricing: {
      label: 'membership',
      title1: 'One community.',
      title2: 'Two tiers.',
      sub: 'The community is the product. Inference is the superpower you add. No upsells, no trial.',
      perVat: '/mo · VAT included',
      perTaxes: '/mo · taxes included',
      inferenceIncluded: 'inference included',
      memberIncludes: [
        'Access to the shared cluster. Open models, no token caps.',
        'DeepSeek V4-Flash (frontier 284B, 1M context, reasoning). 500M tokens/month.',
        'Open models chosen by the community',
        'Personal API key compatible with OpenAI',
        'Private Discord channels for members only',
        'Events, workshops and hackathons',
        'Voice in the quarterly model vote',
      ],
      memberCond: 'Month to month, no commitment. Limited spots: when it fills up, waitlist.',
      memberCta: 'Join the waitlist',
      communityIncludes: [
        'Discord access',
        'Member-only channels',
        'Live discussions, builds, AMAs',
        'Events, workshops and hackathons',
        'A reserved spot in line for inference',
      ],
      communityCond: 'No commitment. Cancel anytime.',
      communityCta: 'Join the community',
    },
    who: {
      label: "who's behind",
      title: 'The NaN community is led by Cristian Córdova and Borja Perez.',
      quote:
        'I started NaN because I wanted to run serious open models without usage limits, and share and learn with people in the same boat: builders who actually burn tokens.',
      quoteBy: 'Cristian Córdova',
      cristianRole: 'Founder of Helmcode',
      cristianLoc: 'Tenerife, Islas Canarias',
      cristianBio: [
        'Founder of Helmcode, working with startups on cloud infrastructure, AI tooling and open source.',
        'Thanks to Helmcode we offer open model inference with unlimited token plans for enterprises. I share my experiments on social media and AI research.',
      ],
      borjaRole: 'Marketing Lead',
      borjaLoc: 'Valencia, Spain',
      borjaBio: [
        'Builder with marketing skills. Helping Cristian with comms and community.',
        'Our goal is to create the best open-models community in the world, helping people create and ship products with open AI.',
      ],
    },
    faq: {
      label: 'faq',
      title: "What you'll probably ask.",
      items: [
        {
          q: 'What is NaN?',
          a: "A closed community of builders sharing dedicated GPUs to run open models. Every member pays to be here, and there's only room for people who actually build.",
        },
        {
          q: 'How does the cluster work?',
          a: "The models run 24/7 on a shared inference cluster. Each member gets a personal API key compatible with OpenAI: change the base_url and you're in.",
        },
        {
          q: 'Is it really unlimited tokens?',
          a: 'On the cluster models, no counter. The frontier ones (like DeepSeek V4-Flash) come with 500M tokens/month per member so the plan holds up. That limit is published here, not in fine print. The bill is the fixed subscription price and it doesn’t move.',
        },
        {
          q: 'How are the models chosen?',
          a: 'Every quarter members vote on Discord which new models join the cluster. Candidates are pre-selected technically: they have to fit the real capacity. The open ecosystem moves fast, and so does the cluster.',
        },
        {
          q: 'Where does my data go?',
          a: 'Processed in the European Union, with no logging of prompts or responses. Your API key is personal and non-transferable. Your code trains no model and your data never leaves your session.',
        },
        {
          q: 'Who is NaN for?',
          a: "Builders who want to run open models seriously without building the infrastructure: indie hackers, makers, people with agents and side projects in production. It's not for someone who just wants to try a couple of prompts.",
        },
        {
          q: 'Why only open models?',
          a: 'Because they can be audited, modified and used without asking permission. Closed ones are convenient but create dependency. With open models, the stack is yours.',
        },
        {
          q: 'Can I train models?',
          a: 'No. NaN is inference, not training. The GPUs are optimized to run existing models at high speed, not for fine-tuning.',
        },
        {
          q: 'What payment methods do you accept?',
          a: 'Credit or debit card. Prices include taxes (VAT in the EU, taxes in USA/Latam). No commitment: cancel anytime.',
        },
        {
          q: 'How do I get in?',
          a: "Leave your email on the waitlist and we'll write when a spot opens. There's a waitlist because there are no more GPUs: when compute comes in, people come in.",
        },
      ],
    },
    footer: {
      cta1: 'Start building.',
      cta2: 'Start burning tokens.',
      go: 'Join the waitlist',
      privacy: 'Privacy',
      terms: 'Terms',
      cookies: 'Cookies',
      community: 'Community',
      notice:
        "We use strictly necessary cookies to run the site. No analytics, no advertising, no cross-site tracking, ever.",
      copyPre: 'NaN is the inference community of',
      copyRights: 'All rights reserved.',
      copyFrom: 'From Canary Islands to 🌎',
      colExplore: 'explore',
      colLegal: 'legal',
      colConnect: 'connect',
    },
    cookie: {
      title: 'Purrr',
      line1: "We don't track cookies, but...",
      q: 'Do you love cats?',
      yes: 'Yes',
      yesIDo: 'Yes, I do',
    },
    notFound: {
      metaTitle: '404 — NaN',
      eyebrow: 'error 404 // no tokens',
      title1: 'This page ran',
      title2: 'out of tokens.',
      body:
        "The address you typed doesn't exist, or it never did. Either way, there's nothing to render here. You, though, still fit here.",
      back: 'Back to home',
      join: 'Join the waitlist',
    },
    projects: {
      metaTitle: 'Projects — NaN',
      metaDesc: 'What the NaN community is building.',
      eyebrow: '// projects',
      title: 'Community projects.',
      subPre: 'What the NaN community is building. Star your favourites on',
      filterAll: 'all',
      groupTop: 'top projects',
      groupAll: '// all projects',
      openApp: 'Open app ↗',
      viewRepo: 'View repo ↗',
    },
    docs: {
      metaTitle: 'Docs — NaN',
      metaDesc: 'Connect your tools to the NaN cluster. OpenAI-compatible API.',
      eyebrow: '// docs',
      navIntro: 'Introduction',
      navGetting: 'Getting Started',
      navModels: 'Models',
      navExamples: 'Examples',
      navSupport: 'Support',
      title: 'Welcome to NaN.',
      leadA:
        'This doc explains how to connect your tools to our GPUs. The cluster runs open models with an OpenAI-compatible API. If something accepts a ',
      leadB: ', it works with NaN.',
      apiKeyH: 'Your API key',
      apiKeyP1:
        'To get your API key you must be a NaN community member. Generate it from your user settings under ',
      apiKeyStrong: 'API Keys',
      apiKeyP2: ' on ',
      apiKeyP3: '. It is personal and non-transferable.',
      rateLimitsH: 'Rate limits',
      rpmK: 'requests per minute',
      parK: 'max parallel',
      nextH: 'What to do next',
      next: [
        { t: 'Getting Started', d: 'Endpoint, auth and setup. Point any OpenAI-compatible client at the cluster.' },
        { t: 'Models', d: 'The full catalogue, capabilities and limits.' },
        { t: 'Examples', d: 'Snippets in Python, Node.js and curl.' },
        { t: 'Support', d: 'Ask in the #support channel on Discord.' },
      ],
    },
    events: {
      metaTitle: 'Events — NaN',
      metaDesc: 'Workshops, events and hackathons inside the NaN community.',
      heroEyebrow: '// events',
      heroTitle1: 'Live inside',
      heroTitle2: 'the community.',
      heroSub:
        'Workshops, events and hackathons happen inside NaN. The recordings live in the community. You log in to watch them.',
      membersOnly: 'members only',
      loginToSee: 'Log in to see it',
      monthLabel: 'this month in nan',
      monthTitle: 'This month in NaN.',
      monthSub: 'The next 30 days. The community proposes and votes the agenda on Discord.',
      monthLockTitle: 'members only',
      monthLockBody: 'The full agenda lives inside the community.',
      weekdays: ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'],
      monthEmpty: 'Nothing scheduled in the next 30 days yet. The community proposes the agenda on Discord.',
      types: { workshop: 'workshop', event: 'event', hackathon: 'hackathon' },
      workshopsLabel: 'workshops',
      workshopsTitle: 'Workshops.',
      workshopsSub: 'Hands-on sessions on agents, tooling and shipping with open models. Recorded for members.',
      eventsLabel: 'events',
      eventsTitle: 'Events.',
      eventsSub: 'Community moments: milestones, AMAs and get-togethers.',
      hackathonsLabel: 'hackathons',
      hackathonsTitle: 'Hackathons.',
      hackathonsSub: 'Build weeks on the cluster. Teams, a theme and a demo day.',
      watchNote: 'log in to watch',
      hackathon: {
        blurb:
          "7 days to build with the cluster's open source models. Teams of 4, balanced. Prize: 1 month of NaN free.",
        when: 'June 7-13 · build week · Sunday 14th: Demo Day',
        allowed: 'Allowed models: Qwen 3.6 or Gemma 4. The project must be open source. Free theme.',
        statusLabel: 'registration closed',
        statusBody: 'The registration window has closed. We hope to see you at the next NaN hackathon!',
      },
    },
    community: {
      metaTitle: 'Community — NaN',
      metaDesc: 'NaN is the springboard for builders shipping with open AI. Build in public, together.',
      heroEyebrow: '// the NaN community',
      heroTitle: 'Create. Share. Help.',
      heroSub:
        'NaN is the springboard for builders shipping with open AI. Here we Build in Public: you show what you make, you learn from the rest and you ship with company.',
      ctaPrimary: 'Join the community',
      ctaSecondary: 'See the roadmap',
      whatLabel: 'what happens here',
      whatTitle: 'A community to build, not just to burn tokens',
      whatIntro:
        'Everything we run in the NaN community has one goal: that you leave with something learned, something built, or someone new to build with.',
      pillars: [
        {
          name: 'Discord',
          body: "Where the community lives. This is where the events, the announcements and the day-to-day happen: model discussions, papers worth reading, deployment questions and whatever you are building.",
          freq: 'always open · the meeting point',
        },
        {
          name: 'Events, workshops and hackathons',
          body: 'Hands-on learning every month. We bring in people who know their stuff to run sessions on AI, open source and everything around building with open models. And we run hackathons to challenge ourselves to build products.',
          freq: '1x/month sessions · 1x/quarter hackathon',
        },
        {
          name: 'Built with NaN',
          body: 'The community projects section. We help builders get visibility for what they build: we amplify the best projects on social with the NaN and Helmcode megaphone.',
          freq: 'your project, in front of more people',
        },
        {
          name: 'Café Helmcode',
          body: 'The in-person event. A coffee across different cities to put faces to names, talk without rushing and build as a community. Because some conversations only happen away from a screen.',
          freq: 'city by city · see you soon',
        },
      ],
      progressLabel: 'in progress',
      progressTitle: 'What we are cooking',
      progressIntro: 'Three initiatives already under construction.',
      inProgressTag: 'in progress',
      initiatives: [
        {
          name: 'NaN Combinator',
          body: 'Our incubator for builders. We want product companies to be born out of NaN, and we will help however we can: training in sales, product, marketing and scaling. Every 6 months we will run a small cohort to help build and scale their ideas, with a Demo Day at the end. The goal: that soon you can say that cool product you use was built in the community.',
        },
        {
          name: 'Ambassador Plan',
          body: "NaN's ambassador program. Our way of rewarding the people who spread the word: we help you set up and host events on behalf of NaN. Ambassadors are picked from the community, on merit. If you are already moving NaN on your own, this is about giving you fuel.",
        },
        {
          name: 'Open source collaborative project',
          body: 'A NaN repo maintained by everyone. It could be a useful library, a Spanish benchmark of open models or a dataset. What matters: that it belongs to the community, serves the ecosystem and has your name in the commits.',
        },
      ],
      roadmapLabel: 'roadmap',
      roadmapTitle: 'What is coming',
      roadmapIntro:
        'We have a lot of plans, but we cannot tackle everything at once. So we go step by step, and in the open.',
      membersLabel: 'nan_members',
      membersNow: 450,
      membersGoal: 1000,
      roadmapColInitiative: 'initiative',
      roadmapColStatus: 'status',
      roadmap: [
        { initiative: '1,000 members', detail: "this year's goal", status: 'in_progress' },
        { initiative: 'Ambassador program', detail: 'pilot with someone from the community', status: 'next' },
        { initiative: 'Recurring online events', detail: 'workshops, webinars, talks; ambassadors tearing apart the repo of the moment, or AMAs with outside guests (people from Hugging Face, for example)', status: 'in_progress' },
        { initiative: 'In-person event', detail: 'if we gather enough people', status: 'soon' },
        { initiative: 'Hackathons', detail: '1 per quarter; some with a partner and cool prizes', status: 'planned' },
        { initiative: 'Community projects', detail: "spotlight and launch projects through Helmcode's channels; maybe even a quarterly Demo Day", status: 'planned' },
        { initiative: 'Mini-challenges', detail: "weekend challenges, model battles, 'kill the wrapper' rounds cloning products", status: 'planned' },
      ],
      closeTitle: 'Build together',
      closeText:
        'If you are building with open AI, or you want to start, this is your place. Come in, introduce yourself and show us what you are working on.',
      closeCta: 'Join the community',
    },
  },

  es: {
    meta: {
      title: 'NaN — Construye sin límites',
      siteName: 'NaN',
      ogLocale: 'es_ES',
      description:
        'Una comunidad de builders que comparten GPUs para correr modelos abiertos a tarifa fija. API compatible con OpenAI, cero logs, plazas limitadas por cómputo.',
    },
    // strings que solo ve la tecnología asistiva. {x} = hueco a sustituir.
    a11y: {
      skip: 'Saltar al contenido',
      brandHome: 'NaN, inicio',
      menuOpen: 'Abrir menú',
      menuClose: 'Cerrar menú',
      navPrimary: 'Principal',
      navLegal: 'Legal',
      navDocs: 'Secciones de la documentación',
      language: 'Idioma',
      email: 'Email',
      region: 'Región',
      close: 'Cerrar',
      cookies: 'Aviso de cookies',
      projectDetail: 'Detalle del proyecto',
      openProject: 'Abrir {name}',
      projectsRail: 'Proyectos de la comunidad, carrusel horizontal',
      membersOnly: '{title}, solo para miembros',
      gpuDither: 'NVIDIA RTX 5090, ilustración con trama',
    },
    nav: {
      models: 'Modelos',
      community: 'Comunidad',
      events: 'Eventos',
      projects: 'Proyectos',
      docs: 'Docs',
      login: 'Entrar',
    },
    hero: {
      line1: 'Construye sin',
      line2: 'límites.',
      sub: 'No te quedes sin tokens. Nunca.',
      body:
        'NaN es la comunidad de builders que comparten GPUs para correr modelos de IA abiertos. Construye lo que necesites, sin límite de tokens. You can just do things.',
      spots: 'Plazas limitadas',
      waitline: 'Únete a la waitlist para activar tu suscripción. Solo deja tu email.',
      emailPlaceholder: 'tu@email.dev',
      regionLabel: 'Elige tu región',
      submit: 'Únete a la waitlist',
      // estados del envío (los lee waitlist.ts desde data-* del <form>)
      sending: 'Enviando…',
      okRegistered: 'Ya estás en la waitlist.',
      okPosition: 'posición',
      okText: 'Aprobaremos tu plaza en los próximos días. No pierdas de vista tu bandeja ^__^',
      errEmail: 'Ese email no parece válido.',
      errRegion: 'Elige una región.',
      errNetwork: 'Ha fallado la red, no tú. Prueba otra vez.',
      errGeneric: 'Algo se ha roto por nuestro lado. Prueba en un rato.',
    },
    why: {
      label: 'qué es nan',
      title1: 'Qué es NaN.',
      title2: 'La comunidad de builders',
      lead: 'Builders compartiendo GPUs dedicadas para correr modelos abiertos y quemar tokens sin límites.',
      p: [
        'Las APIs de modelos cerrados son cómodas, pero caras y limitadas. Los modelos abiertos son libres, pero correrlos en serio exige un hardware que casi nadie tiene en casa.',
        'NaN lo resuelve compartiendo GPUs potentes entre builders que de verdad las usan, repartiendo el coste real de la infraestructura.',
        'Una comunidad cerrada por diseño, limitada a la capacidad real de las GPUs compartidas. Cuando se llena, abrimos waitlist.',
        'La comunidad vive en Discord. La web solo gestiona el acceso. Cada miembro paga por estar aquí. Solo entra quien de verdad quiere construir.',
      ],
    },
    built: {
      label: 'hecho con nan',
      title1: 'No quemamos tokens.',
      title2: 'Construimos.',
      sub: 'Proyectos reales hechos por miembros de NaN sobre el cluster de inferencia compartido. Esto es lo que pasa cuando los builders tienen hardware de verdad.',
      railLabel: 'proyectos de la comunidad',
      seeAll: 'Ver todos los proyectos',
      addYours: 'Añade el tuyo',
    },
    models: {
      label: 'el cluster',
      titleSuffix: 'modelos.',
      titleLine2: 'Una API.',
      sub: 'Todo el stack de inferencia de modelos abiertos, votado por la comunidad cada trimestre. Los datos se quedan en la UE, sin registrar nada.',
      unmetered: 'sin contador',
      cta: 'Únete a la waitlist',
    },
    privacy: {
      label: 'privacidad',
      title1: 'Pura inferencia.',
      title2: 'Cero logs.',
      intro:
        'NaN es infraestructura de inferencia. No se registran prompts, ni respuestas del modelo, nada. Todo vive en tu sesión local, en el cliente, agente o app que uses.',
      guarantees: [
        'Cero logs. Ni prompts ni respuestas quedan registrados.',
        'Todo vive en tu cliente local o en la sesión de tu agente.',
        'Procesado en la Unión Europea.',
        'Tu código no entrena ningún modelo.',
        'Solo métricas de servidor, para mantenimiento del cluster (tokens/s, RPM).',
      ],
      termNote: '# 0 bytes. 0 filas. nada almacenado, por diseño.',
      termFoot: 'saliendo del servidor: tokens/s · RPM · métricas del cluster',
    },
    pricing: {
      label: 'membresía',
      title1: 'Una comunidad.',
      title2: 'Dos tiers.',
      sub: 'La comunidad es el producto. La inferencia es el superpoder que le añades. Sin upsells, sin trial.',
      perVat: '/mes · IVA incluido',
      perTaxes: '/mes · impuestos incluidos',
      inferenceIncluded: 'inferencia incluida',
      memberIncludes: [
        'Acceso al cluster compartido. Modelos abiertos, sin límite de tokens.',
        'DeepSeek V4-Flash (frontier 284B, contexto 1M, razonamiento). 500M tokens/mes.',
        'Modelos abiertos elegidos por la comunidad',
        'API key personal compatible con OpenAI',
        'Canales privados de Discord solo para miembros',
        'Eventos, workshops y hackathons',
        'Voto en la votación trimestral de modelos',
      ],
      memberCond: 'Mes a mes, sin compromiso. Plazas limitadas: cuando se llena, waitlist.',
      memberCta: 'Únete a la waitlist',
      communityIncludes: [
        'Acceso a Discord',
        'Canales solo para miembros',
        'Charlas en directo, builds, AMAs',
        'Eventos, workshops y hackathons',
        'Un sitio reservado en la cola de inferencia',
      ],
      communityCond: 'Sin compromiso. Cancela cuando quieras.',
      communityCta: 'Únete a la comunidad',
    },
    who: {
      label: 'quién está detrás',
      title: 'La comunidad NaN la lideran Cristian Córdova y Borja Perez.',
      quote:
        'Monté NaN porque quería correr modelos abiertos de los buenos sin límites de uso, y compartir y aprender con gente que está en la misma: builders que queman tokens de verdad.',
      quoteBy: 'Cristian Córdova',
      cristianRole: 'Founder de Helmcode',
      cristianLoc: 'Tenerife, Islas Canarias',
      cristianBio: [
        'Founder de Helmcode, trabajando con startups en infraestructura cloud, AI tooling y open source.',
        'Gracias a Helmcode ofrecemos inferencia de modelos abiertos con planes de tokens ilimitados para empresas. Comparto mis experimentos en redes y mi research de IA.',
      ],
      borjaRole: 'Marketing Lead',
      borjaLoc: 'Valencia, España',
      borjaBio: [
        'Builder con habilidades de marketing. Ayudo a Cristian con la comunicación y la comunidad.',
        'Nuestra meta es crear la mejor comunidad de modelos abiertos del mundo, ayudando a la gente a crear y lanzar productos con IA abierta.',
      ],
    },
    faq: {
      label: 'faq',
      title: 'Lo que probablemente vas a preguntar.',
      items: [
        {
          q: '¿Qué es NaN?',
          a: 'Una comunidad cerrada de builders que comparten GPUs dedicadas para correr modelos abiertos. Cada miembro paga por estar aquí, y solo hay sitio para gente que de verdad construye.',
        },
        {
          q: '¿Cómo funciona el cluster?',
          a: 'Los modelos corren 24/7 en un cluster de inferencia compartido. Cada miembro recibe una API key personal compatible con OpenAI: cambias el base_url y ya estás dentro.',
        },
        {
          q: '¿De verdad son tokens ilimitados?',
          a: 'En los modelos del cluster, sin contador. Los frontier (como DeepSeek V4-Flash) llevan 500M tokens/mes por miembro para que el plan se sostenga. Ese límite está publicado aquí, no en letra pequeña. La factura es el precio fijo de la suscripción y no se mueve.',
        },
        {
          q: '¿Cómo se eligen los modelos?',
          a: 'Cada trimestre los miembros votan en Discord qué modelos nuevos entran al cluster. Los candidatos se preseleccionan técnicamente: tienen que caber en la capacidad real. El ecosistema abierto se mueve rápido, y el cluster también.',
        },
        {
          q: '¿A dónde van mis datos?',
          a: 'Se procesan en la Unión Europea, sin registrar prompts ni respuestas. Tu API key es personal e intransferible. Tu código no entrena ningún modelo y tus datos nunca salen de tu sesión.',
        },
        {
          q: '¿Para quién es NaN?',
          a: 'Para builders que quieren correr modelos abiertos en serio sin montar la infraestructura: indie hackers, makers, gente con agentes y side projects en producción. No es para quien solo quiere probar un par de prompts.',
        },
        {
          q: '¿Por qué solo modelos abiertos?',
          a: 'Porque se pueden auditar, modificar y usar sin pedir permiso. Los cerrados son cómodos pero crean dependencia. Con modelos abiertos, el stack es tuyo.',
        },
        {
          q: '¿Puedo entrenar modelos?',
          a: 'No. NaN es inferencia, no entrenamiento. Las GPUs están optimizadas para correr modelos existentes a alta velocidad, no para fine-tuning.',
        },
        {
          q: '¿Qué métodos de pago aceptáis?',
          a: 'Tarjeta de crédito o débito. Los precios incluyen impuestos (IVA en la UE, impuestos en USA/Latam). Sin compromiso: cancela cuando quieras.',
        },
        {
          q: '¿Cómo entro?',
          a: 'Deja tu email en la waitlist y te escribimos cuando se abra una plaza. Hay waitlist porque no hay más GPUs: cuando entra cómputo, entra gente.',
        },
      ],
    },
    footer: {
      cta1: 'Empieza a construir.',
      cta2: 'Empieza a quemar tokens.',
      go: 'Únete a la waitlist',
      privacy: 'Privacidad',
      terms: 'Términos',
      cookies: 'Cookies',
      community: 'Comunidad',
      notice:
        'Usamos solo cookies estrictamente necesarias para que la web funcione. Sin analytics, sin publicidad, sin tracking entre sitios, nunca.',
      copyPre: 'NaN es la comunidad de inferencia de',
      copyRights: 'Todos los derechos reservados.',
      copyFrom: 'Desde Canarias hasta 🌎',
      colExplore: 'explora',
      colLegal: 'legal',
      colConnect: 'conecta',
    },
    cookie: {
      title: 'Purrr',
      line1: 'No rastreamos cookies, pero...',
      q: '¿Te gustan los gatos?',
      yes: 'Sí',
      yesIDo: 'Sí, me encantan',
    },
    notFound: {
      metaTitle: '404 — NaN',
      eyebrow: 'error 404 // sin tokens',
      title1: 'Esta página se quedó',
      title2: 'sin tokens.',
      body:
        'La dirección que escribiste no existe, o nunca existió. En cualquier caso, aquí no hay nada que renderizar. Tú, en cambio, sí encajas aquí.',
      back: 'Volver al inicio',
      join: 'Únete a la waitlist',
    },
    projects: {
      metaTitle: 'Proyectos — NaN',
      metaDesc: 'Lo que está construyendo la comunidad NaN.',
      eyebrow: '// proyectos',
      title: 'Proyectos de la comunidad.',
      subPre: 'Lo que está construyendo la comunidad NaN. Marca tus favoritos con una estrella en',
      filterAll: 'todos',
      groupTop: 'top proyectos',
      groupAll: '// todos los proyectos',
      openApp: 'Abrir app ↗',
      viewRepo: 'Ver repo ↗',
    },
    docs: {
      metaTitle: 'Docs — NaN',
      metaDesc: 'Conecta tus herramientas al cluster de NaN. API compatible con OpenAI.',
      eyebrow: '// docs',
      navIntro: 'Introducción',
      navGetting: 'Primeros pasos',
      navModels: 'Modelos',
      navExamples: 'Ejemplos',
      navSupport: 'Soporte',
      title: 'Bienvenido a NaN.',
      leadA:
        'Esta doc explica cómo conectar tus herramientas a nuestras GPUs. El cluster corre modelos abiertos con una API compatible con OpenAI. Si algo acepta un ',
      leadB: ', funciona con NaN.',
      apiKeyH: 'Tu API key',
      apiKeyP1:
        'Para conseguir tu API key tienes que ser miembro de la comunidad NaN. Genérala desde los ajustes de tu usuario, en ',
      apiKeyStrong: 'API Keys',
      apiKeyP2: ', en ',
      apiKeyP3: '. Es personal e intransferible.',
      rateLimitsH: 'Rate limits',
      rpmK: 'peticiones por minuto',
      parK: 'máx. en paralelo',
      nextH: 'Qué hacer ahora',
      next: [
        { t: 'Primeros pasos', d: 'Endpoint, auth y setup. Apunta cualquier cliente compatible con OpenAI al cluster.' },
        { t: 'Modelos', d: 'El catálogo completo, capacidades y límites.' },
        { t: 'Ejemplos', d: 'Snippets en Python, Node.js y curl.' },
        { t: 'Soporte', d: 'Pregunta en el canal #support de Discord.' },
      ],
    },
    events: {
      metaTitle: 'Eventos — NaN',
      metaDesc: 'Workshops, eventos y hackathons dentro de la comunidad NaN.',
      heroEyebrow: '// eventos',
      heroTitle1: 'Vive dentro',
      heroTitle2: 'de la comunidad.',
      heroSub:
        'Los workshops, eventos y hackathons pasan dentro de NaN. Las grabaciones viven en la comunidad. Entras para verlas.',
      membersOnly: 'solo miembros',
      loginToSee: 'Entra para verlo',
      monthLabel: 'este mes en nan',
      monthTitle: 'Este mes en NaN.',
      monthSub: 'Los próximos 30 días. La comunidad propone y vota la agenda en Discord.',
      monthLockTitle: 'solo miembros',
      monthLockBody: 'La agenda completa vive dentro de la comunidad.',
      weekdays: ['lun', 'mar', 'mié', 'jue', 'vie', 'sáb', 'dom'],
      monthEmpty: 'Nada programado en los próximos 30 días todavía. La comunidad propone la agenda en Discord.',
      types: { workshop: 'workshop', event: 'evento', hackathon: 'hackathon' },
      workshopsLabel: 'workshops',
      workshopsTitle: 'Workshops.',
      workshopsSub: 'Sesiones prácticas sobre agentes, tooling y lanzar con modelos abiertos. Grabadas para miembros.',
      eventsLabel: 'eventos',
      eventsTitle: 'Eventos.',
      eventsSub: 'Momentos de la comunidad: hitos, AMAs y quedadas.',
      hackathonsLabel: 'hackathons',
      hackathonsTitle: 'Hackathons.',
      hackathonsSub: 'Semanas de build sobre el cluster. Equipos, un tema y un demo day.',
      watchNote: 'entra para verlo',
      hackathon: {
        blurb:
          '7 días para construir con los modelos open source del cluster. Equipos de 4, equilibrados. Premio: 1 mes de NaN gratis.',
        when: '7-13 de junio · semana de build · domingo 14: Demo Day',
        allowed: 'Modelos permitidos: Qwen 3.6 o Gemma 4. El proyecto tiene que ser open source. Tema libre.',
        statusLabel: 'inscripción cerrada',
        statusBody: 'La ventana de inscripción se ha cerrado. ¡Esperamos verte en el próximo hackathon de NaN!',
      },
    },
    community: {
      metaTitle: 'Comunidad — NaN',
      metaDesc: 'NaN es el trampolín para builders que construyen con IA abierta. Build in public, en comunidad.',
      heroEyebrow: '// la comunidad de NaN',
      heroTitle: 'Crear. Compartir. Ayudar.',
      heroSub:
        'NaN es el trampolín para builders que construyen con IA abierta. Aquí hacemos Build in Public: enseñas lo que haces, aprendes de los demás y lanzas acompañado.',
      ctaPrimary: 'Únete a la comunidad',
      ctaSecondary: 'Ver el roadmap',
      whatLabel: 'qué pasa aquí',
      whatTitle: 'Una comunidad para construir, no solo para quemar tokens',
      whatIntro:
        'Todo lo que montamos en la comunidad de NaN tiene un objetivo: que salgas con algo aprendido, algo construido o alguien nuevo con quien construir.',
      pillars: [
        {
          name: 'Discord',
          body: 'Donde vive la comunidad. Aquí pasan los eventos, los anuncios y las conversaciones de cada día: discusiones sobre modelos, papers que merecen la pena, dudas de despliegue y lo que estés construyendo.',
          freq: 'siempre abierto · el punto de encuentro',
        },
        {
          name: 'Eventos, workshops y hackatones',
          body: 'Formación práctica cada mes. Traemos a gente que sabe a dar sesiones sobre IA, open source y todo lo que rodea a construir con modelos abiertos. Y montamos hackatones para ponernos retos de construir productos.',
          freq: '1x mes formativos · 1x trimestre hackatón',
        },
        {
          name: 'Built with NaN',
          body: 'La sección de proyectos de la comunidad. Ayudamos a los builders a dar visibilidad a lo que construyen: los mejores proyectos los potenciamos en redes con el altavoz de NaN y Helmcode.',
          freq: 'tu proyecto, delante de más gente',
        },
        {
          name: 'Café Helmcode',
          body: 'El evento en persona. Un café por diferentes ciudades para ponernos cara, hablar sin prisa y construir en comunidad. Porque hay conversaciones que solo pasan fuera de una pantalla.',
          freq: 'ciudad a ciudad · nos vemos pronto',
        },
      ],
      progressLabel: 'en marcha',
      progressTitle: 'Lo que estamos cocinando',
      progressIntro: 'Tres iniciativas que ya están en construcción.',
      inProgressTag: 'in progress',
      initiatives: [
        {
          name: 'NaN Combinator',
          body: 'Nuestra incubadora para builders. Queremos que nazcan empresas de producto desde NaN, y vamos a ayudarles en todo lo posible: formaciones de ventas, producto, marketing y escalado. Cada 6 meses montaremos una pequeña cohorte para ayudar a construir y escalar sus ideas, con su Demo Day al final. El objetivo: que dentro de poco puedas decir que ese producto tan guay que usas se construyó en la comunidad.',
        },
        {
          name: 'Ambassador Plan',
          body: 'El plan de embajadores de NaN. Nuestra manera de recompensar a quienes difunden la palabra: te ayudamos a montar y alojar eventos en nombre de NaN. Los embajadores se seleccionan de entre la comunidad, por méritos. Si ya estás moviendo NaN por tu cuenta, esto va de darte gasolina.',
        },
        {
          name: 'Proyecto colaborativo open source',
          body: 'Un repo de NaN mantenido entre todos. Puede ser una librería útil, un benchmark en español de modelos abiertos o un dataset. Lo importante: que sea de la comunidad, que sirva al ecosistema y que tu nombre esté en los commits.',
        },
      ],
      roadmapLabel: 'roadmap',
      roadmapTitle: 'Lo que viene',
      roadmapIntro:
        'Tenemos muchos planes, pero no todo se puede atacar a la vez. Así que vamos paso a paso, y en abierto.',
      membersLabel: 'nan_members',
      membersNow: 450,
      membersGoal: 1000,
      roadmapColInitiative: 'iniciativa',
      roadmapColStatus: 'estado',
      roadmap: [
        { initiative: '1.000 miembros', detail: 'el objetivo de este año', status: 'in_progress' },
        { initiative: 'Ambassador program', detail: 'piloto con alguien de la comunidad', status: 'next' },
        { initiative: 'Eventos online periódicos', detail: 'workshops, webinars, charlas; embajadores destripando el repo del momento, o AMAs con invitados externos (gente de Hugging Face, por ejemplo)', status: 'in_progress' },
        { initiative: 'Evento presencial', detail: 'si juntamos suficiente gente', status: 'soon' },
        { initiative: 'Hackatones', detail: '1 por trimestre; algunos con partner y premios guays', status: 'planned' },
        { initiative: 'Proyectos de la comunidad', detail: 'destacar y lanzar proyectos por los canales de Helmcode; quizás incluso un Demo Day trimestral', status: 'planned' },
        { initiative: 'Mini-retos', detail: "retos de fin de semana, batallas de modelos, rondas de 'kill the wrapper' clonando productos", status: 'planned' },
      ],
      closeTitle: 'Construye acompañado',
      closeText:
        'Si estás construyendo con IA abierta, o quieres empezar, este es tu sitio. Entra, preséntate y enséñanos lo que traes entre manos.',
      closeCta: 'Únete a la comunidad',
    },
  },
};
export default ui;
