/// <reference types="astro/client" />

// Mirrors the shape generated by `wrangler types` into
// `worker-configuration.d.ts` (which is gitignored). Declaring it here keeps
// CI type-checking green even when the wrangler-generated file is absent,
// and TS will merge both declarations when it IS present locally.
declare namespace Cloudflare {
  interface Env {
    RESEND_API_KEY: string;
    RESEND_FROM_EMAIL: string;
    CLOUD_API_URL: string;
    CLOUD_API_WAITLIST_KEY: string;
  }
}

interface Env extends Cloudflare.Env {}
